#' Prediction of heavy rain and cicadas noises
#' The function computes a random forest model to classify the minutes of a database into three categories: Clean, Rain and Cicada
#' @param data A dataset generated by the function \code{\link[ANECO]{acoustic_indices}} (the option \code{"noise.ind = TRUE"} must have been included in the function \code{\link[ANECO]{acoustic_indices}})
#' @param mod A previously fitted random forest model to classify the data according to the selected indices.
#'
#' @return
#' A dataset with the classification of each minute of the original dataset with its respective identification
#' @export
#'
soundclassifier_predict <- function(data = NULL, mod = NULL){

  #chequear si estan todas las columnas
  indnames <- c("msldBA_bio", "msldBA_low", "mdBGL", "SpecIQR", "SpecKurt", "SpecSkew", "SpecQ3","SpecCent", "S2N_chi", "dfreq", "E01", "E12", "E23", "E34", "E45", "E56", "E67", "E78", "E89", "E910", "E1011")

  if(!all(indnames %in% colnames(data))){
    stop("Incomplete database. Must contain acoustic indices for noise detection (noise.ind = TRUE) in the acoustic_indices function: 'msldBA_bio', 'msldBA_low', 'mdBGL', 'SpecIQR', 'SpecKurt', 'SpecSkew', 'SpecQ3','SpecCent', 'S2N_chi', 'dfreq', 'E01', 'E12', 'E23', 'E34', 'E45', 'E56', 'E67', 'E78', 'E89', 'E910', 'E1011'")
    }

  clmnsID <- c("Name", "Code", "Site", "RecorderID", "Date", "Year","Month", "Day", "Hour", "Minute")

  if(!all(clmnsID %in% colnames(data))){
  stop("Incomplete database. It must contain the columns for identification that are included in the result of the acoustic_indices function: 'Name', 'Code', 'Site', 'RecorderID', 'Date', 'Year', 'Month', 'Day', 'Hour', 'Minute' ")
  }

  #seleccionar columnas de indices
  datos <- data[, which(colnames(data) %in% indnames)]

  #seleccionar columnas de identificacion
  id <- data[, which(colnames(data) %in% clmnsID)]

  # predecir utilizando el modelo
  rf_predclas <- predict(mod, newdata = datos, type = "raw")

  resultado <- data.frame(id, Prediccion = rf_predclas)
  return(resultado)
}
